engines:
  rubocop:
    enabled: true
  brakeman:
   	enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
  	enabled: true
ratings:
  paths:
  - singularity/**
  - inc/**
  - "**.asm"
  - "**.inc"
exclude_paths:
- engine/**